# Generated by Django 4.2.11 on 2024-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stresslevelrecord_is_suicide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresslevelrecord',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stresslevelrecord',
            name='is_suicide',
            field=models.CharField(max_length=20),
        ),
    ]
