# Generated by Django 4.2.11 on 2024-03-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stresslevelrecord_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresslevelrecord',
            name='bmi_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stresslevelrecord',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stresslevelrecord',
            name='is_suicide',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stresslevelrecord',
            name='stress_level',
            field=models.CharField(max_length=100),
        ),
    ]
